{'data': {'attributes': {'can_chat': True,
                         'can_control': True,
                         'can_control_video_feed': True,
                         'can_take_control': True,
                         'chat_room_channel': 'organization_1823_1179944981',
                         'dates': 'May 9, 2021',
                         'live_channel': 'live_1823_1179944981_plan_52371712_1617898160',
                         'series_title': "Mother's Day",
                         'title': None},
          'id': '52371712',
          'links': {'controller': 'https://api.planningcenteronline.com/services/v2/people/2476970',
                    'current_item_time': 'https://api.planningcenteronline.com/services/v2/service_types/824571/plans/52371712/live/current_item_time',
                    'go_to_next_item': 'https://api.planningcenteronline.com/services/v2/service_types/824571/plans/52371712/live/go_to_next_item',
                    'go_to_previous_item': 'https://api.planningcenteronline.com/services/v2/service_types/824571/plans/52371712/live/go_to_previous_item',
                    'items': 'https://api.planningcenteronline.com/services/v2/service_types/824571/plans/52371712/live/items',
                    'next_item_time': 'https://api.planningcenteronline.com/services/v2/service_types/824571/plans/52371712/live/next_item_time',
                    'self': 'https://api.planningcenteronline.com/services/v2/service_types/824571/plans/52371712/live',
                    'service_type': 'https://api.planningcenteronline.com/services/v2/service_types/824571',
                    'toggle_control': 'https://api.planningcenteronline.com/services/v2/service_types/824571/plans/52371712/live/toggle_control',
                    'watchable_plans': 'https://api.planningcenteronline.com/services/v2/service_types/824571/plans/52371712/live/watchable_plans'},
          'type': 'Live'},
 'included': [],
 'meta': {'can_include': ['controller',
                          'current_item_time',
                          'items',
                          'next_item_time',
                          'service_type'],
          'parent': {'id': '52371712', 'type': 'Plan'}}}
None